import type { Member, Org, SoftifyRecord } from './types'

const now = Date.now()
const iso = (offsetMs: number) => new Date(now + offsetMs).toISOString()
const day = 86_400_000
const hour = 3_600_000

export const ORG: Org = {
  id: 'org_softify',
  name: 'Softify',
  plan: 'Studio',
}

export const MEMBERS: Member[] = [
  {
    id: 'user_panos',
    name: 'Πρόδρομος Βασιλόπουλος',
    email: 'info@softify.gr',
    role: 'Founder',
    hue: 250,
  },
  {
    id: 'user_maria',
    name: 'Μαρία Κώστα',
    email: 'maria@helix.studio',
    role: 'Sales',
    hue: 20,
  },
  {
    id: 'user_nikos',
    name: 'Νίκος Ανδρέου',
    email: 'nikos@helix.studio',
    role: 'Delivery',
    hue: 160,
  },
  {
    id: 'user_elena',
    name: 'Elena Rossi',
    email: 'elena@helix.studio',
    role: 'Success',
    hue: 300,
  },
  {
    id: 'user_jordan',
    name: 'Jordan Lee',
    email: 'jordan@helix.studio',
    role: 'Finance',
    hue: 45,
  },
]

export const CURRENT_USER_ID = 'user_panos'

function rec(
  partial: Omit<SoftifyRecord, 'createdAt' | 'updatedAt'> & {
    createdAt?: string
    updatedAt?: string
  },
): SoftifyRecord {
  return {
    createdAt: iso(-4 * day),
    updatedAt: iso(-2 * hour),
    ...partial,
  }
}

export const DEMO_RECORDS: SoftifyRecord[] = [
  rec({
    id: 'co_helios',
    type: 'company',
    title: 'Helios Bank',
    fields: {
      domain: 'heliosbank.gr',
      industry: 'Finance',
      size: '2,400',
      city: 'Athens',
      health: 'strong',
    },
    relations: [],
  }),
  rec({
    id: 'co_aegean',
    type: 'company',
    title: 'Aegean Logistics',
    fields: {
      domain: 'aegeanlog.com',
      industry: 'Logistics',
      size: '860',
      city: 'Piraeus',
      health: 'ok',
    },
    relations: [],
  }),
  rec({
    id: 'co_nimbus',
    type: 'company',
    title: 'Nimbus Health',
    fields: {
      domain: 'nimbus.health',
      industry: 'Health',
      size: '320',
      city: 'Thessaloniki',
      health: 'strong',
    },
    relations: [],
  }),
  rec({
    id: 'co_polar',
    type: 'company',
    title: 'Polar Studio',
    fields: {
      domain: 'polar.studio',
      industry: 'Media',
      size: '42',
      city: 'Lisbon',
      health: 'ok',
    },
    relations: [],
  }),
  rec({
    id: 'co_orion',
    type: 'company',
    title: 'Orion Retail',
    fields: {
      domain: 'orion-retail.eu',
      industry: 'Retail',
      size: '1,100',
      city: 'Milan',
      health: 'risk',
    },
    relations: [],
  }),
  rec({
    id: 'co_kite',
    type: 'company',
    title: 'Kite Coffee',
    fields: {
      domain: 'kitecoffee.gr',
      industry: 'Hospitality',
      size: '70',
      city: 'Athens',
      health: 'strong',
    },
    relations: [],
  }),
  rec({
    id: 'ct_sofia',
    type: 'contact',
    title: 'Sofia Markou',
    fields: {
      role: 'CTO',
      email: 'sofia.markou@heliosbank.gr',
      phone: '+30 210 555 0192',
    },
    relations: [{ kind: 'company', id: 'co_helios' }],
  }),
  rec({
    id: 'ct_andreas',
    type: 'contact',
    title: 'Andreas Vlachos',
    fields: {
      role: 'Head of Ops',
      email: 'andreas@aegeanlog.com',
      phone: '+30 210 555 0118',
    },
    relations: [{ kind: 'company', id: 'co_aegean' }],
  }),
  rec({
    id: 'ct_irene',
    type: 'contact',
    title: 'Irene Papadimitriou',
    fields: {
      role: 'CPO',
      email: 'irene@nimbus.health',
      phone: '+30 231 055 0440',
    },
    relations: [{ kind: 'company', id: 'co_nimbus' }],
  }),
  rec({
    id: 'ct_lucas',
    type: 'contact',
    title: 'Lucas Almeida',
    fields: {
      role: 'Founder',
      email: 'lucas@polar.studio',
      phone: '+351 21 555 0090',
    },
    relations: [{ kind: 'company', id: 'co_polar' }],
  }),
  rec({
    id: 'ct_chiara',
    type: 'contact',
    title: 'Chiara Bianchi',
    fields: {
      role: 'IT Director',
      email: 'chiara@orion-retail.eu',
      phone: '+39 02 555 0177',
    },
    relations: [{ kind: 'company', id: 'co_orion' }],
  }),
  rec({
    id: 'dl_helios_core',
    type: 'deal',
    title: 'Core banking portal',
    fields: {
      stage: 'negotiation',
      amount: 84000,
      closeDate: iso(12 * day),
      ownerId: 'user_maria',
      probability: 70,
      sort: 0,
    },
    relations: [
      { kind: 'company', id: 'co_helios' },
      { kind: 'contact', id: 'ct_sofia' },
    ],
    updatedAt: iso(-3 * hour),
  }),
  rec({
    id: 'dl_nimbus_app',
    type: 'deal',
    title: 'Patient experience app',
    fields: {
      stage: 'qualified',
      amount: 120000,
      closeDate: iso(28 * day),
      ownerId: 'user_panos',
      probability: 45,
      sort: 0,
    },
    relations: [
      { kind: 'company', id: 'co_nimbus' },
      { kind: 'contact', id: 'ct_irene' },
    ],
  }),
  rec({
    id: 'dl_aegean_fleet',
    type: 'deal',
    title: 'Fleet operating system',
    fields: {
      stage: 'proposal',
      amount: 46500,
      closeDate: iso(9 * day),
      ownerId: 'user_maria',
      probability: 55,
      sort: 0,
    },
    relations: [
      { kind: 'company', id: 'co_aegean' },
      { kind: 'contact', id: 'ct_andreas' },
    ],
  }),
  rec({
    id: 'dl_orion_pos',
    type: 'deal',
    title: 'POS modernization',
    fields: {
      stage: 'proposal',
      amount: 62000,
      closeDate: iso(18 * day),
      ownerId: 'user_elena',
      probability: 40,
      sort: 1,
    },
    relations: [
      { kind: 'company', id: 'co_orion' },
      { kind: 'contact', id: 'ct_chiara' },
    ],
  }),
  rec({
    id: 'dl_polar_brand',
    type: 'deal',
    title: 'Brand system & site',
    fields: {
      stage: 'lead',
      amount: 18000,
      closeDate: iso(21 * day),
      ownerId: 'user_panos',
      probability: 25,
      sort: 0,
    },
    relations: [
      { kind: 'company', id: 'co_polar' },
      { kind: 'contact', id: 'ct_lucas' },
    ],
  }),
  rec({
    id: 'dl_kite_loyalty',
    type: 'deal',
    title: 'Loyalty & ordering',
    fields: {
      stage: 'lead',
      amount: 9400,
      closeDate: iso(30 * day),
      ownerId: 'user_maria',
      probability: 20,
      sort: 1,
    },
    relations: [{ kind: 'company', id: 'co_kite' }],
  }),
  rec({
    id: 'dl_helios_kyc',
    type: 'deal',
    title: 'Mobile KYC',
    fields: {
      stage: 'won',
      amount: 36000,
      closeDate: iso(-14 * day),
      ownerId: 'user_maria',
      probability: 100,
      sort: 0,
    },
    relations: [{ kind: 'company', id: 'co_helios' }],
  }),
  rec({
    id: 'dl_north_lost',
    type: 'deal',
    title: 'Internal wiki rebuild',
    fields: {
      stage: 'lost',
      amount: 22000,
      closeDate: iso(-20 * day),
      ownerId: 'user_panos',
      probability: 0,
      sort: 0,
    },
    relations: [{ kind: 'company', id: 'co_polar' }],
  }),
  rec({
    id: 'pr_helios',
    type: 'project',
    title: 'Helios Core Portal',
    fields: {
      status: 'active',
      target: iso(45 * day),
      ownerId: 'user_nikos',
      color: '#7c9cff',
    },
    relations: [
      { kind: 'company', id: 'co_helios' },
      { kind: 'deal', id: 'dl_helios_core' },
    ],
  }),
  rec({
    id: 'pr_nimbus',
    type: 'project',
    title: 'Nimbus Patient App',
    fields: {
      status: 'active',
      target: iso(70 * day),
      ownerId: 'user_panos',
      color: '#5eead4',
    },
    relations: [
      { kind: 'company', id: 'co_nimbus' },
      { kind: 'deal', id: 'dl_nimbus_app' },
    ],
  }),
  rec({
    id: 'pr_aegean',
    type: 'project',
    title: 'Aegean Fleet OS',
    fields: {
      status: 'planning',
      target: iso(90 * day),
      ownerId: 'user_nikos',
      color: '#f5c16c',
    },
    relations: [
      { kind: 'company', id: 'co_aegean' },
      { kind: 'deal', id: 'dl_aegean_fleet' },
    ],
  }),
  rec({
    id: 'pr_internal',
    type: 'project',
    title: 'SoftifyOS studio build',
    fields: {
      status: 'active',
      target: iso(21 * day),
      ownerId: 'user_panos',
      color: '#c4a6ff',
    },
    relations: [],
  }),
  rec({
    id: 'tk_1',
    type: 'task',
    title: 'Map Helios SSO + role matrix',
    fields: {
      status: 'in_progress',
      priority: 'high',
      due: iso(1 * day),
      ownerId: 'user_nikos',
      sort: 0,
    },
    relations: [{ kind: 'project', id: 'pr_helios' }],
  }),
  rec({
    id: 'tk_2',
    type: 'task',
    title: 'Proposal deck for Aegean ops team',
    fields: {
      status: 'review',
      priority: 'urgent',
      due: iso(0),
      ownerId: 'user_maria',
      sort: 0,
    },
    relations: [{ kind: 'project', id: 'pr_aegean' }],
  }),
  rec({
    id: 'tk_3',
    type: 'task',
    title: 'Patient onboarding flow, v2',
    fields: {
      status: 'backlog',
      priority: 'medium',
      due: iso(5 * day),
      ownerId: 'user_panos',
      sort: 0,
    },
    relations: [{ kind: 'project', id: 'pr_nimbus' }],
  }),
  rec({
    id: 'tk_4',
    type: 'task',
    title: 'Design OS command palette',
    fields: {
      status: 'done',
      priority: 'high',
      due: iso(-1 * day),
      ownerId: 'user_panos',
      sort: 0,
    },
    relations: [{ kind: 'project', id: 'pr_internal' }],
  }),
  rec({
    id: 'tk_5',
    type: 'task',
    title: 'Contract redlines with legal',
    fields: {
      status: 'in_progress',
      priority: 'urgent',
      due: iso(-1 * day),
      ownerId: 'user_jordan',
      sort: 1,
    },
    relations: [{ kind: 'project', id: 'pr_helios' }],
  }),
  rec({
    id: 'tk_6',
    type: 'task',
    title: 'Nimbus HIPAA / GDPR checklist',
    fields: {
      status: 'backlog',
      priority: 'high',
      due: iso(3 * day),
      ownerId: 'user_elena',
      sort: 1,
    },
    relations: [{ kind: 'project', id: 'pr_nimbus' }],
  }),
  rec({
    id: 'tk_7',
    type: 'task',
    title: 'QA telemetry dashboard',
    fields: {
      status: 'review',
      priority: 'medium',
      due: iso(2 * day),
      ownerId: 'user_nikos',
      sort: 1,
    },
    relations: [{ kind: 'project', id: 'pr_helios' }],
  }),
  rec({
    id: 'tk_8',
    type: 'task',
    title: 'Kickoff agenda for Polar',
    fields: {
      status: 'backlog',
      priority: 'low',
      due: iso(8 * day),
      ownerId: 'user_elena',
      sort: 2,
    },
    relations: [{ kind: 'project', id: 'pr_internal' }],
  }),
  rec({
    id: 'tk_9',
    type: 'task',
    title: 'Invoice schedule for Mobile KYC',
    fields: {
      status: 'done',
      priority: 'medium',
      due: iso(-3 * day),
      ownerId: 'user_jordan',
      sort: 1,
    },
    relations: [{ kind: 'project', id: 'pr_helios' }],
  }),
  rec({
    id: 'tk_10',
    type: 'task',
    title: 'Record demo of CRM + Work graph',
    fields: {
      status: 'in_progress',
      priority: 'medium',
      due: iso(2 * day),
      ownerId: 'user_panos',
      sort: 2,
    },
    relations: [{ kind: 'project', id: 'pr_internal' }],
  }),
  rec({
    id: 'doc_handbook',
    type: 'doc',
    title: 'Studio handbook',
    fields: {
      emoji: '◈',
      body: 'Helix Partners is a product studio. We ship operating systems for ambitious teams — CRM, delivery, and finance in one graph.\n\nHow we work\n• One owner per record.\n• Write decisions down the same day.\n• Prefer a smaller surface that feels inevitable.\n\nThis OS is the source of truth. If it is not in SoftifyOS, it did not happen.',
    },
    relations: [],
  }),
  rec({
    id: 'doc_playbook',
    type: 'doc',
    title: 'Sales playbook',
    fields: {
      emoji: '◎',
      body: 'We sell outcomes, not hours.\n\n1. Qualify on urgency, budget, and a named owner.\n2. Map the current toolchain — usually 5 to 8 apps.\n3. Demo the graph: a deal that becomes a project without export.\n4. Close on a 90-day studio sprint, then retain.\n\nNever leave a call without a next record in the OS.',
    },
    relations: [],
  }),
  rec({
    id: 'doc_helios',
    type: 'doc',
    title: 'Helios kickoff notes',
    fields: {
      emoji: '⬡',
      body: 'Sofia wants the portal live before the Q4 board. Constraints: existing Keycloak, branch-level permissions, Greek + English.\n\nOpen questions\n– Do relationship managers see only their book?\n– Can we replace the Excel pipeline this quarter?\n\nDecision: start with the kernel (identity, records, activity) and ship the first loan-officer workspace in 6 weeks.',
    },
    relations: [
      { kind: 'company', id: 'co_helios' },
      { kind: 'deal', id: 'dl_helios_core' },
    ],
  }),
  rec({
    id: 'doc_voice',
    type: 'doc',
    title: 'Brand voice',
    fields: {
      emoji: '◻',
      body: 'Calm, precise, a little warm. We sound like a senior partner, not a startup hype deck.\n\nYes: “The record is the source of truth.”\nNo: “Revolutionize your workflow with AI.”\n\nAI is a colleague with excellent memory and no ego. It suggests. Humans commit.',
    },
    relations: [],
  }),
  rec({
    id: 'ev_1',
    type: 'event',
    title: 'Helios negotiation',
    fields: {
      start: iso(2 * hour),
      end: iso(3 * hour),
      location: 'Meet · Sofia Markou',
    },
    relations: [{ kind: 'deal', id: 'dl_helios_core' }],
  }),
  rec({
    id: 'ev_2',
    type: 'event',
    title: 'Studio standup',
    fields: {
      start: iso(-1 * hour),
      end: iso(0.25 * hour),
      location: 'Helix HQ',
    },
    relations: [{ kind: 'project', id: 'pr_internal' }],
  }),
  rec({
    id: 'ev_3',
    type: 'event',
    title: 'Nimbus product workshop',
    fields: {
      start: iso(day + 3 * hour),
      end: iso(day + 5 * hour),
      location: 'Thessaloniki · hybrid',
    },
    relations: [{ kind: 'deal', id: 'dl_nimbus_app' }],
  }),
  rec({
    id: 'ev_4',
    type: 'event',
    title: 'Aegean proposal review',
    fields: {
      start: iso(2 * day + 4 * hour),
      end: iso(2 * day + 5.5 * hour),
      location: 'Zoom',
    },
    relations: [{ kind: 'deal', id: 'dl_aegean_fleet' }],
  }),
  rec({
    id: 'ev_5',
    type: 'event',
    title: 'Finance close',
    fields: {
      start: iso(3 * day + 2 * hour),
      end: iso(3 * day + 3 * hour),
      location: 'Jordan + Panos',
    },
    relations: [],
  }),
  rec({
    id: 'in_1',
    type: 'inbox',
    title: 'Board wants a live portal date',
    fields: {
      channel: 'email',
      read: false,
      from: 'Sofia Markou',
      preview:
        'Can we lock a public beta before 12 Oct? I will take it to the board on Friday.',
    },
    relations: [
      { kind: 'deal', id: 'dl_helios_core' },
      { kind: 'contact', id: 'ct_sofia' },
    ],
    createdAt: iso(-40 * 60_000),
  }),
  rec({
    id: 'in_2',
    type: 'inbox',
    title: 'Maria mentioned you in Aegean proposal',
    fields: {
      channel: 'mention',
      read: false,
      from: 'Μαρία Κώστα',
      preview: '@panos can you review the integration slide before 16:00?',
    },
    relations: [{ kind: 'deal', id: 'dl_aegean_fleet' }],
    createdAt: iso(-2 * hour),
  }),
  rec({
    id: 'in_3',
    type: 'inbox',
    title: 'KYC invoice marked paid',
    fields: {
      channel: 'notif',
      read: true,
      from: 'SoftifyOS',
      preview: 'Helios Bank · Mobile KYC · €36,000 received.',
    },
    relations: [{ kind: 'deal', id: 'dl_helios_kyc' }],
    createdAt: iso(-6 * hour),
  }),
  rec({
    id: 'in_4',
    type: 'inbox',
    title: 'Chiara asked for a security appendix',
    fields: {
      channel: 'email',
      read: false,
      from: 'Chiara Bianchi',
      preview: 'Procurement needs pen-test summary + data residency before we sign.',
    },
    relations: [{ kind: 'deal', id: 'dl_orion_pos' }],
    createdAt: iso(-26 * hour),
  }),
  rec({
    id: 'in_5',
    type: 'inbox',
    title: 'Cycle review tomorrow',
    fields: {
      channel: 'notif',
      read: true,
      from: 'Work',
      preview: '4 tasks still open on Helios Core Portal.',
    },
    relations: [{ kind: 'project', id: 'pr_helios' }],
    createdAt: iso(-day),
  }),
  rec({
    id: 'ac_1',
    type: 'activity',
    title: 'moved deal to Negotiation',
    fields: { actorId: 'user_maria', verb: 'moved' },
    relations: [{ kind: 'deal', id: 'dl_helios_core' }],
    createdAt: iso(-3 * hour),
  }),
  rec({
    id: 'ac_2',
    type: 'activity',
    title: 'created Patient experience app',
    fields: { actorId: 'user_panos', verb: 'created' },
    relations: [{ kind: 'deal', id: 'dl_nimbus_app' }],
    createdAt: iso(-9 * hour),
  }),
  rec({
    id: 'ac_3',
    type: 'activity',
    title: 'completed Design OS command palette',
    fields: { actorId: 'user_panos', verb: 'completed' },
    relations: [{ kind: 'task', id: 'tk_4' }],
    createdAt: iso(-day),
  }),
  rec({
    id: 'ac_4',
    type: 'activity',
    title: 'commented on Fleet operating system',
    fields: { actorId: 'user_elena', verb: 'commented' },
    relations: [{ kind: 'deal', id: 'dl_aegean_fleet' }],
    createdAt: iso(-5 * hour),
  }),
]
